# This workflow runs all dockerfiles in this repo

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  matrix_prep:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - id: set-matrix
        name: Prepare matrix from Dockerfiles in repo
        run: | 
          matrix=$(find . -type f -name "Dockerfile" -printf "{\"folder\":\"%h\"}," | sed -e 's/,$//')         
          echo "Matrix: $matrix"
          echo ::set-output name=matrix::{\"include\":[$(echo $matrix)]}

  docker_run:
    needs: matrix_prep
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
      
    steps:
      - uses: actions/checkout@v2
                
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            folder:
              - '${{matrix.folder}}/**'  
        
        # This steps makes everything
        # Builds the image by Dockerfile
        # Runs the image
        # Test if console output is "Hello World!"
      - name: Build, run and test Image
        if: steps.changes.outputs.folder == 'true'
        run: | 
          cd ${{matrix.folder}}
          docker build . --tag $(basename $(pwd))
          docker run $(basename $(pwd))
          [[ docker logs $(docker ps --all -l --format "{{.ID}}") == "Hello World!" ]] && echo "Output matches 'Hello World!'." || echo "Output does not match 'Hello World!'." && exit 1
